---
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - 4000:80
      - 443:443 # for ssl
    depends_on:
      - web
    networks:
      - nginx_web
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: .env.production
    networks:
      - nginx_web
networks:
  nginx_web:
